spring:
  application:
    name: mcpwithspring-client
  # main:
  #   web-application-type: none
  ai:
    mcp:
      client:
        enabled: true
        name: mcp-client-poc
        version: 0.1.0
        request-timeout: 30s
        type: ASYNC
        toolcallback:
          enabled: true
        sse:
          connections:
            mcp-server-poc:
              url: http://localhost:8080
        stdio:
          connections:
            filesystem:
              command: npx
              args:
                - "-y"
                - "@modelcontextprotocol/server-filesystem"
                - ${user.home}
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          maxCompletionTokens: 8000

server:
  port: 8081

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
